# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170809_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='api.Employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(through='api.Manager', to='api.Employee'),
        ),
    ]
