# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employee_performance_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='performance_review',
        ),
    ]
