# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_employee_performance_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance_review',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
